### ISSUE TITLE
More simply json/yaml format

### ISSUE THREAD

**Issue by tac0x2a** [tac0x2a/yasuri#26]
## Example
```json
{
  "map_simple_elements": {
    "text_hoge": "//*[@id='contents']/h2",
    "text_fuga": "//*[@id='contents']/p[1]"
  },
  "links_nested_elements": {
    "path": "//*[@id='menu']/ul/li/a",
    "text_hoge": {"path": "//*[@id='contents']/h2", "truncate": "/^[^,]+/"},
    "text_fuga": {"path": "//*[@id='contents']/p[1]", "proc": ":upcase"}
  }
}
```

```yaml
map_simple_elements:
  text_hoge: "//*[@id='contents']/h2"
  text_fuga: "//*[@id='contents']/h2"

links_nested_elements:
  path: "//*[@id='menu']/ul/li/a"
  text_hoge:
    path: "//*[@id='contents']/h2"
    truncate: "/^[^,]+/"
  text_fuga: {"path": "//*[@id='contents']/p[1]", "proc": ":upcase"}
```

## Expected Result
```json
{
  "simple_elements":{
    "hoge": "hogehoge-",
    "fuga": "fugafuga-"
  },
  "nested_elements": [
    {
      "hoge": "hogehoge- p1",
      "fuga": "fugafuga- p1"
    },
    {
      "hoge": "hogehoge- p2",
      "fuga": "fugafuga- p2"
    }
  ]
}
```
